name: gitops-introduction

services:
  server:
    image: traefik:v3.5
    ports:
      - 80:80
      # - 443:443 TLS requires more setup than this intro allows
      # - 8080:8080 # Uncomment this and the command below to enable Traefik's dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # "--api.insecure=true" # Uncomment this and the port above to enable Traefik's dashboard
  
  example-service:
    image: stefanprodan/podinfo
    environment:
      - PODINFO_UI_COLOR=111827
      - PODINFO_UI_MESSAGE=Welcome to the brand new app!
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example-service.rule=PathPrefix(`/`)"
      - "traefik.http.services.example-service.loadbalancer.server.port=9898"
